name: Appium Java Android Application Automation CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install Appium server and Android driver
      - name: Install Appium server and Appium Android driver
        run: |
          npm install -g appium@next
          echo "APPIUM_VERSION=next" >> $GITHUB_ENV
          echo "APPIUM_DRIVER=uiautomator2" >> $GITHUB_ENV

  test:
    runs-on: macos-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      # Access environment variables for Appium and Android driver
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - run: echo $APPIUM_VERSION
      - run: echo $APPIUM_DRIVER

      - name: Start Appium server
        run: |
          appium &>/dev/null &

      - name: Execute Android test suite
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn clean test -Pandroid,qa

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports
